# Thrustmaster T FlightStick X
# The joy stick joy message is mapped like 
# axis
#     0:  Left / Right
#     1:  Forward/Back
#     2:  Rotate Stick
#     3:  Thrust Forward/Back
#     4:  Rocket Left / Right
#     5:  Rocket Forward/Back
# button
#     0:  Fire
#     1:  Fire Rocket
#     2:  Button 3
#     3:  Button 4
#     4:  Button 5
#     5:  Button 6
#     6:  Button 7
#     7:  Button 8
#     8:  Button 9
#     9:  Button 10
#     10:  Button 11
#     11:  Button 12

teleop_twist:
  ros__parameters:
# Whether to require the enable button for enabling movement.      
    require_enable_button: false
# Joystick axis to use for linear movement control.
    axis_linear:  # Forward/Back
      x: 1
# Scale to apply to joystick linear axis for regular-speed movement.    
    scale_linear:
      x: 0.7
# Scale to apply to joystick linear axis for high-speed movement.
    scale_linear_turbo:
      x: 1.5

# Joystick axis to use for linear movement control.
    axis_linear:  # Left / Right
      y: 0
# Scale to apply to joystick linear axis for regular-speed movement.    
    scale_linear:
      y: 0.7
# Scale to apply to joystick linear axis for high-speed movement.
    scale_linear_turbo:
      y: 1.5

# Joystick axis to use for angular movement control.
    axis_angular:  # Twist
      yaw: 2
# Scale to apply to joystick angular axis.
    scale_angular:
      yaw: 0.4

    enable_button: 0  # Trigger fire button (1)
    enable_turbo_button: 1  # Button 2 aka Fire rocket button (2)
